# Use Java 17 base image
FROM eclipse-temurin:17-jdk

# Set working directory inside container
WORKDIR /app

# Copy everything from your repo into the container
COPY . .

# Build your Spring Boot app
RUN ./mvnw clean install -DskipTests

# Run the application
CMD ["java", "-jar", "target/E-commerce-0.0.1-SNAPSHOT.jar"]
